# version: '3.8'

services:
  db:
      image: postgres:15-alpine
      restart: always
      env_file:
        - .env
      ports:
        - "5433:5432" # <-- Đổi 5432 thành 5433 ở bên trái
      volumes:
        - postgres_data:/var/lib/postgresql/data

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend/app:/app/app
    # Ghi đè lệnh CMD trong Dockerfile để bật tính năng hot-reload khi code ở máy tính
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 

  admin-frontend:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://api.amidemy.uk/api/v1
    ports:
      - "3000:80" # Map port 80 trong container ra 3000 trên host (hoặc port bạn muốn)
    restart: always

volumes:
  postgres_data:
